export const WMO_MAP = {
  0: { text: "Clear sky", emoji: "☀️" },
  1: { text: "Mainly clear", emoji: "🌤️" },
  2: { text: "Partly cloudy", emoji: "⛅" },
  3: { text: "Overcast", emoji: "☁️" },
  45: { text: "Fog", emoji: "🌫️" },
  48: { text: "Depositing rime fog", emoji: "🌫️" },
  51: { text: "Drizzle: light", emoji: "🌦️" },
  53: { text: "Drizzle: moderate", emoji: "🌦️" },
  55: { text: "Drizzle: dense", emoji: "🌦️" },
  56: { text: "Freezing drizzle: light", emoji: "🌧️❄️" },
  57: { text: "Freezing drizzle: dense", emoji: "🌧️❄️" },
  61: { text: "Rain: slight", emoji: "🌦️" },
  63: { text: "Rain: moderate", emoji: "🌧️" },
  65: { text: "Rain: heavy", emoji: "🌧️🌧️" },
  66: { text: "Freezing rain: light", emoji: "🌧️❄️" },
  67: { text: "Freezing rain: heavy", emoji: "🌧️❄️❄️" },
  71: { text: "Snow fall: slight", emoji: "🌨️" },
  73: { text: "Snow fall: moderate", emoji: "🌨️❄️" },
  75: { text: "Snow fall: heavy", emoji: "🌨️❄️❄️" },
  77: { text: "Snow grains", emoji: "❄️" },
  80: { text: "Rain showers: slight", emoji: "🌦️" },
  81: { text: "Rain showers: moderate", emoji: "🌧️" },
  82: { text: "Rain showers: violent", emoji: "🌧️🌩️" },
  85: { text: "Snow showers: slight", emoji: "🌨️" },
  86: { text: "Snow showers: heavy", emoji: "❄️🌨️" },
  95: { text: "Thunderstorm: slight or moderate", emoji: "🌩️" },
  96: { text: "Thunderstorm with slight hail", emoji: "🌩️❄️" },
  99: { text: "Thunderstorm with heavy hail", emoji: "🌩️❄️❄️" },
};